# This workflow will build a node-Js application, and cache/restore any dependencies to improve the workflow execution time
# Create the secret DOCKER_HUB_USERNAME and DOCKER_HUB_USERNAME

name: GitHub Action Node Js application

on:
  push:
    branches:
    - master
    - release/*"
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Node-Js application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
          # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
         # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
         # Log out from the Docker registry at the end of a job
        #logout: false

    - name: Build and Tag Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-application:${{ github.sha }} .
      
    - name: Push Docker Image to DockerHub      
      run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-application:${{ github.sha }}
